query AnimeDetails($id: Int!) {
  Media(id: $id, type: ANIME) {
    ...AnimeCacheFields
    relations {
      edges {
        relationType(version: 3)
        node {
          type
          ...AnimeCardFields
        }
      }
    }
    recommendations(page: 1, perPage: 10, sort: [RATING_DESC]) {
      nodes {
        rating
        mediaRecommendation {
          type
          ...AnimeCardFields
        }
      }
    }
    characters(page: 1, perPage: 12, sort: [ROLE, RELEVANCE]) {
      edges {
        role
        node {
          id
          name { full }
          image { large medium }
        }
        voiceActors(language: JAPANESE, sort: [RELEVANCE]) {
          id
          name { full }
        }
      }
    }
    externalLinks {
      id
      url
      site
      type
      language
      icon
      notes
      isDisabled
    }
  }
}
